### ISSUE TITLE
CUSPARSE_SPMM_CSR(COO) for out-of-bound indices

### ISSUE THREAD

**Issue by tlu7** [NVIDIA/CUDALibrarySamples#106]
What is the default behavior of handling out-of-bound indices for cusparse SpMM COO and CSR? Do I expect a segmentation fault? How about the indices are sorted and out of bound? Could you share some pointers on the underlying algorithm for these senarios? I think we hit on some corner cases while lowering JAX sparse matmul to cusparse. Thanks!

**Comment by tlu7** [comment]
@fbusato

**Comment by fbusato** [comment]
Out-of-bound indices (independently if they are sorted or unsorted) are not supported in any cuSPARSE routines. They lead to out-of-bound memory accesses that is a non-recoverable error and the application must be closed.

**Comment by tlu7** [comment]
@jakevdp

**Comment by jakevdp** [comment]
Thanks for the info @fbusato. One quick followup: what about out-of-bound indices in CSR that are out of the range of the `indptr` array? For example, imagine you had a CSR representation that looks like this:
```python
shape = (3, 5)
indptr = [0, 3, 4, 7]
indices = [1, 2, 4, 0, 1, 3, 4, 99, 99, 99, 99, 99]
```
The `99` entries are out of bounds, but they are beyond the seven values that any algorithm should need to access, according to the pointer array. Would it be safe to pass this data into a cusparse matmul?

The context of these questions is our work on lowering `jax.experimental.sparse` operations to cusparse kernels; because of the static array size constraints of JAX, our sparse representation needs a way to pad its sparse representation. Our current model fills unnecessary indices with out-of-bound values, but there's a cost to correcting these before lowering to cusparse that eats into the computational efficiency that we get from that lowering.

**Comment by fbusato** [comment]
Everything outside the normal bounds of a given format (COO, CSR, etc.) is not accessed by cuSPARSE kernels. In other words, it is perfectly fine to add any value outside the boundaries, e.g. `99` in your case

**Comment by tlu7** [comment]
Thanks a lot for answering our questions!

**Comment by jakevdp** [comment]
Hi @fbusato – I found an issue related to the question above: for CSR SpMV, it appears that the final value in `indptr` is not respected if it is less than nnz. I was able to reproduce the issue on CUDA 11.6 with this data:
```
# Sparse matrix
shape=(3, 4)
data = [1., 2., 3., 4.]
indices = [0, 1, 2, 3]
indptr = [0, 1, 2, 3]  # Note final value is 3, so only the first three
                       # values of data/indices should be referenced.

# Vector
v = [1., 2., 3., 4.]
```
The output of `cusparseSpMV` with this input is:
```
[ 1.  4. 25.]
```
I would expect the output to be:
```
[1. 4. 9.]
```
Here is a Colab notebook reproducing the issue via JAX, which calls into cusparse on the GPU: https://colab.research.google.com/drive/1wALy4KjK-alL95gsg_QoWWGLxkJDMjcW

**Comment by qanhpham** [comment]
Hi @jakevdp, when creating the sparse matrix using `cusparseCreateCsr`, the `nnz` parameter is provided. In your case, the `nnz` is still 4 (probably from the length of `data` or `indices`). If the `nnz` parameter is set to 3, the result will be correct.

**Comment by jakevdp** [comment]
Thanks - so should my mental model be that cusparse always ignores the last entry of indptr, and effectively uses nnz in its place? What’s the purpose of the last entry if its value is ignored?

**Comment by qanhpham** [comment]
In this particular SpMV routine, the last entry isn't used. You actually can put any value to it. The `nnz` parameter determines how many entries will be processed in SpMV.

**Comment by jakevdp** [comment]
Thanks for the info – I'm not sure how to act on this, because (as far as I understand, correct me if I'm wrong) the final entry of indptr lives on the GPU device, and so it can't easily be extracted to the `cusparseCreateCsr` constructor.

To be more concrete, how would you modify the code here to act on the fact that `nnz` in `gpusparseCreateCsr` should be replaced with the last entry of `csr_row_offsets`? https://github.com/google/jax/blob/658a934821eeec15dd6cd47a7056191f8231de24/jaxlib/gpu/sparse_kernels.cc#L258-L261

**Comment by qanhpham** [comment]
You're right. The `indptr` is on GPU memory. The only way to get the `nnz` is copying the entry `csr_row_offsets[rows + 1]` to CPU memory (using `cudaMemcpy`).

**Comment by jakevdp** [comment]
I'm worried that copying that value to host will lead to a performance penalty, since it would require host/device synchronization. Is there any possibility that CUDA's CsrSpMV could be updated to take into account the upper bound specified in `csr_row_offsets`?

**Comment by qanhpham** [comment]
We already have `nnz` parameter for number of entries to process. It'll be confusing & complicated to take another parameter into account.
Note that, the `nnz` can be set once at the creation of sparse matrix. You don't have to get its value each time doing SpMV.

**Comment by jakevdp** [comment]
I see - thanks. The issue is in JAX's use of cusparse, the matrix must be created on-demand when SpMV is called, and the "true" nnz is already defined on the device, and is not available on the host. I guess we'll have to continue adding the extra pass over the buffers to zero-out all values larger than the dynamic nnz before calling SpMV. If you can think of any other way around this, please let us know!

**Comment by jakevdp** [comment]
One other question: in cusparse CSR SpMM, the above behavior doesn't seem to be an issue. Perhaps SpMM is coded more robustly? So perhaps our best solution would be to stop using `SpMV` in favor of reshaping the inputs & outputs and calling SpMM instead.

**Comment by qanhpham** [comment]
It seems that only `CUSPARSE_SPMM_CSR_ALG3` takes upper bound of `csr_row_offsets` as the number of entries.
The `CUSPARSE_SPMM_CSR_ALG1` and `CUSPARSE_SPMM_CSR_ALG2` still rely on `nnz` of sparse matrix.
It could be a good idea to use SpMM as a **batched** SpMV as long as the reshaping overhead isn't costly in your case.
