### ISSUE TITLE
cusparse version for CUSPARSE_SPMM_COO_ALG4

### ISSUE THREAD

**Issue by tlu7** [NVIDIA/CUDALibrarySamples#112]
Hi,

May I know which cuda or cusparse release version starts supporting CUSPARSE_SPMM_COO_ALG4? Need to guard the version of jaxlib. We are currently using CUSPARSE_SPMM_COO_ALG2 for row-major case, which is deterministic but less accurate. Planning to switch to CUSPARSE_SPMM_COO_ALG4

**Comment by tlu7** [comment]
@fbusato @jakevdp

**Comment by jakevdp** [comment]
The reason we need to switch is because coo_spmm is producing incorrect outputs in batch mode with CUSPARSE_SPMM_COO_ALG2 (the output has rows of zeros where it should not). This is with cusparse 11.7.1. Please let me know if if would be helpful to provide a repro of this issue; although I'm honestly not sure how to define it aside from using our JAX cusparse lowering rules.

**Comment by tlu7** [comment]
kindly ping. Waiting for CUDA experts' help before making the design decision for JAX.

**Comment by qanhpham** [comment]
We're checking the cusparse version that starts supporting CUSPARSE_SPMM_COO_ALG4.
As @jakevdp said, you can use it from cuda 11.7.1.
