### ISSUE TITLE
nvjpegCreate segmentation fault

### ISSUE THREAD

**Issue by icantfly** [NVIDIA/CUDALibrarySamples#129]
Hi,
i have met a strange bug. My purpose is to use nvjpeg to compress an image for ros publish. CUDA version is 11.1 and when i run samples in my ubuntu1804, it works fine, while segmentation fault in docker with the CUDA version is 11.1 as well. 
I use gdb to find the crush is caused by both ’nvjpegCreate‘ and ‘nvjpegCreateSimple’ whatever decoding or encoding. The md5sum for libnvjpeg.so is same.

I know it may be a environment caused problem,  and I just do not know how to fix this bug.
Thanks

**Comment by zohebk-nv** [comment]
The issue is caused because nvjpeg is unable to find the libnvcuvid.so and crashes. This issue has been fixed in cuda 11.2. To workaround this issue with cuda 11.1, you can use this option when initializing docker: - --gpus '"capabilities=compute,utility,video"'

or set this in the docker file:
`ENV NVIDIA_DRIVER_CAPABILITIES compute,video,utility`

**Comment by icantfly** [comment]
thank you, it seems to be effective, i will try.
