### ISSUE TITLE
[cuSPARSELT] Documentation on 2:4 sparse packed format created by cusparseLtSpMMACompress?

### ISSUE THREAD

**Issue by cj831880** [NVIDIA/CUDALibrarySamples#167]
Where can we find documentation on the 2:4 sparse packed format created by `cusparseLtSpMMACompress`? We tried to consult Section 3.1 in [https://arxiv.org/abs/2104.08378](https://arxiv.org/abs/2104.08378) but the information on the format is, well, sparse. Thank you.

**Comment by fbusato** [comment]
Hi @cj831880, unfortunately, the internal layout of the metadata is only internal because it can change at any time. If you really need to interact with metadata, my suggestion is to take a look at CUTLASS and the reordering routine. https://github.com/NVIDIA/cutlass/blob/b5d8a5d9ccb435268e2215144dca162b0fc6a826/tools/util/include/cutlass/util/host_reorder.h#L83

**Comment by cj831880** [comment]
Thank you @fbusato. Unfortunately CUTLASS performance is terrible for our use case, so we need to leverage the internal 2:4 sparse format used by `cusparseLtSpMMACompress` to reuse computation and improve performance. Any chance we could get documentation on the sparse format regardless? Thank you and happy new year!

**Comment by fbusato** [comment]
Got it. We cannot reveal the internal format at this time. You can even try to combine the CUTLASS reordering routine and cusparselt, but compatibility is not guaranteed. If you really need it, you can try to reach me at my [work email](fbusato@nvidia.com) and I will bring the issue to the PM.
