### ISSUE TITLE
Can not decompress data compressed by nvCOMP using facebook/zstd

### ISSUE THREAD

**Issue by WilliamKyle** [NVIDIA/CUDALibrarySamples#208]
Decompress  data compressed by nvCOMP using nvCOMP is OK, but failed when using facebook/zstd.

```
#include <zstd.h>
#include <fstream>
#include <iostream>
#include <vector>
#include <cuda_runtime.h>
#include <nvcomp.hpp>
#include <nvcomp/lz4.hpp>
#include <nvcomp/nvcompManagerFactory.hpp>

using namespace std;

int main(int argc, char *argv[]) {
    vector<uint8_t> raw_data(1024 * 1024 * 2, 0);
    vector<uint8_t> compressed_data;

    {
        uint8_t *cuda_buf;
        cudaMalloc(reinterpret_cast<void **>(&cuda_buf), raw_data.size());

        size_t *compressed_size;
        cudaMalloc(&compressed_size, sizeof(size_t));

        const size_t compress_chunk_size = 1 << 16;
        nvcompBatchedZstdOpts_t format_opts;
        nvcomp::ZstdManager zstd_manager(compress_chunk_size, format_opts);

        nvcomp::CompressionConfig compress_config = zstd_manager.configure_compression(raw_data.size());

        uint8_t *compressed_buffer;
        cudaMalloc(&compressed_buffer, compress_config.max_compressed_buffer_size);

        zstd_manager.compress(cuda_buf, compressed_buffer, compress_config, compressed_size);

        size_t compressed_data_size;
        cudaMemcpy(&compressed_data_size, compressed_size, sizeof(size_t), cudaMemcpyDeviceToHost);
        compressed_data.resize(compressed_data_size);

        cudaMemcpy(compressed_data.data(), compressed_buffer, compressed_data_size, cudaMemcpyDeviceToHost);
    }
    ofstream("compressed_data.bin", ios::binary).write((char *)compressed_data.data(), compressed_data.size());

    unsigned long long ret = ZSTD_getFrameContentSize(compressed_data.data(), compressed_data.size());
    assert(ret != ZSTD_CONTENTSIZE_UNKNOWN);
    assert(ret != ZSTD_CONTENTSIZE_ERROR); // <- failed here !!!

    return 0;
}
```

**Comment by baliika** [comment]
Hi @WilliamKyle,
Thanks for your message!

Our default high-level interface (HLIF) (`XXXManager`) output is nvCOMP-specific (`BitstreamKind::NVCOMP_NATIVE`): we need to organize our computation in a way, that is optimal for GPUs (introduce data chunks) and we also add supplementary meta-data that simplifies the decompression. Therefore, even though the underlying algorithm being used is Meta's Zstd, the raw output cannot be parsed by other decompressor implementations.

If you'd like to use other decompressor implementations (e.g. Meta's), you need to specify during the instantiation of the HLIF manager `BitstreamKind::RAW`. Note, however, that this mode requires the user to chunk the input data beforehand, so the GPU can optimally parallelize the compression. Each resulting compressed output buffer afterwards can be decompressed by Meta's implementation. The various bitstream modes are detailed in our documentation [here](https://docs.nvidia.com/cuda/nvcomp/cpp_api.html#_CPPv4N6nvcomp13BitstreamKindE).

On the other hand, one can also use the low-level interface (LLIF) directly to operate on already chunked input data. Its output is analogous to the HLIF's `BitstreamKind::RAW` mode, therefore, each compressed output buffer can also be decompressed by Meta's implementation.

We have some examples demonstrating the usage of
- `BitstreamKind::RAW` with the HLIF [here](https://github.com/NVIDIA/CUDALibrarySamples/blob/master/nvCOMP/examples/high_level_quickstart_example.cpp)
- the LLIF [here](https://github.com/NVIDIA/CUDALibrarySamples/blob/master/nvCOMP/examples/low_level_quickstart_example.cpp)

Should you have more questions, please let me know!

**Comment by lee1258561** [comment]
@baliika hello, 

I have a similar use case if this issue here. But instead of compress with nvCOMP and decompress with meta zstd. I was trying to do the other way around, which is compress with zstd at CPU side and send the data to GPU and decompress with nvCOMP. 

Using `BitstreamKind::RAW` works but the nvCOMP decompression performance is quite low in this mode. Which is likely because what you mentioned here that NVCOMP_NATIVE is trying to organized computation in a way, that is optimal for GPUs (introduce data chunks). 

Therefore, I am trying to implement some custom zstd compress on CPU side try to produce compressed data in a format that is acceptable by NVCOMP_NATIVE, with data chunked & metadata / header inserted. 

But I got a bit hard time figuring out how to do this searching the internet. Wondering if you could point me to some example  / code pointer of how this chunking logic is happening / example of how the data look like?

Thanks!

**Comment by lee1258561** [comment]
Thanks a lot @baliika  for sharing the example, this is very useful!

It looks like the most important things I need is:

  - Batch decompress API: `nvcompBatchedZstdDecompressAsync`, which allow me to decompress chunk efficiently in parallel on GPU
  - A way to chunk the data, like `BatchData`

Is there some python binding of this low level API already being exposed, or I would need to introduce it myself. I am working in a python environment. The closest version I can find is Codec.decode(<list of nvcomp arr>). Not sure if that the same batch decomress API, and it also does provide a way to pass in pre allocated output ptrs to reduce an extra copy.

**Comment by baliika** [comment]
Hi @lee1258561,
We did not expose the LLIF through the Python API (yet) so if you use it through Python, you'd need to wrap these yourself.

From an efficiency point of view I'd say the order of efficiency goes like this:
1. (best) Low-level API via `nvcompBatchedZstdDecompressAsync`, because you know the uncompressed size in advance (with chunking, it is going to be your selected chunk size, and the last chunk is going to be somewhat less)
2. High-level API with `BitstreamKind::WITH_UNCOMPRESSED_SIZE`: in this case, the library does not need to determine the uncompressed size before decompression, as this is present in the buffer's first 8 bytes (in unsigned, little-Endian format). This has minimal runtime overhead compared to option 1) - this small runtime overhead basically concentrated in `  std::vector<DecompressionConfig> configure_decompression(...)`
3. High-level API with `BitstreamKind::RAW`. In this case, the decompressor does not know in advance the size to be decompressed, so there is an extra call inside the library that tries to determine the uncompressed size.

Probably there would be value in performing a `configure_decompression(...)` call with an additional pointer argument (`const size_t* decomp_sizes`) so that ``BitstreamKind::RAW` could match the performance of the low-level API. I'll discuss it with my colleagues and it might become part of the API.

**Comment by lee1258561** [comment]
@baliika thanks. I can work on the python binding my self. Thanks for the pointer. 

qq. I notice that your [example](https://github.com/NVIDIA/CUDALibrarySamples/blob/master/nvCOMP/examples/lz4_cpu_compression.cu) is a `.cu` file, in which when I do a little bit of searching means it contain some cuda native code that need to be compiled in another way.

I totally have no experience of that so I am trying to see if there is a way I don't have to touch that route for initial prototyping. 

Is there a c++ version of `nvcompBatchedZstdDecompressAsync` that I could work with instead to potentially make things easier? 

On the otherhand.  If there is any doc in this repo about how to compile this lz4 *.cu* [example](https://github.com/NVIDIA/CUDALibrarySamples/blob/master/nvCOMP/examples/lz4_cpu_compression.cu), would be appreciated if you could point me to that as well in case I ever want to go back and work on it.

**Comment by lee1258561** [comment]
Oh I guess this would be the cpp version of the example I am looking for https://github.com/NVIDIA/CUDALibrarySamples/blob/master/nvCOMP/examples/low_level_quickstart_example.cpp

**Comment by baliika** [comment]
hi @lee1258561,
Good observation. The file has a .cu extension, because we are using `<thrust/...>` within BatchData.h and thrust needs to compile some kernels for initializing device memory. But that is the only thing device-kernel related in those comp/decomp files. Otherwise, every example could be compiled with a regular C++ compiler (with c++11 support), and nvCOMP in general does not require a CUDA compiler to be used. We might improve on these examples in the future by getting rid of thrust to mitigate confusion.

Given we provided a CMakeLists.txt file within the examples, the only thing you need to do is to install a CUDA Toolkit:
https://developer.nvidia.com/cuda-downloads

Once installed you need to add its binary folder (/usr/local/cuda-12.8/bin) to the PATH environment variable, and its library folder (/usr/local/cuda-12.8/lib64/) to the LD_LIBRARY_PATH environment variable - the rest should be handled by CMake.

A while back I compiled a really detailed guide for acquiring 3rd party dependencies as well: https://github.com/NVIDIA/CUDALibrarySamples/blob/master/nvCOMP/examples/README.md - this should help you in acquiring the 3rd party LZ4 library for instance. Similar steps would apply for Zstd.
Exact steps for compiling the Zstd example will be uploaded with the next nvCOMP release.
